### ISSUE TITLE
Default custom transitions

### ISSUE THREAD

**Issue by vanlooverenkoen** [ikbendewilliam/flutter_navigation_generator#1]
It would be nice to have custom transitions in `flutter_navigation_generator` so you don't have to write them again in different projects.

In https://github.com/ikbendewilliam/get_x_navigation_generator we had `transiation` which makes it easier to play around with different transitions without having to write everything again from scratch

**Comment by ikbendewilliam** [comment]
Basic native animations have been added in a new package https://pub.dev/packages/flutter_navigation_generator_animations/
