### ISSUE TITLE
Add path variables

### ISSUE THREAD

**Issue by vanlooverenkoen** [ikbendewilliam/flutter_navigation_generator#12]
It would be nice to have something like this

```
@FlutterRoute(
  routeName: 'my_route/{id}',
)
```

In the first place this would analytics make easier. But can maybe also be used to implement [this](https://github.com/ikbendewilliam/flutter_navigation_generator/issues/7)

**Comment by ikbendewilliam** [comment]
I'm currently experimenting with this, see this branch: https://github.com/ikbendewilliam/flutter_navigation_generator/tree/feature/web-parameters

Feel free to give it a try and let me know your thoughts!

example:
In this case `name` would be added as a query parameter on web as wel as be included in the settings.arguments. 
```dart
@FlutterRoute(
  routeName: '/home/:id/example/:age',
)
class RouteNameWithArguments2 extends StatelessWidget {
  final String id;
  final String? name;
  final int? age;

  const RouteNameWithArguments2({
    required this.id,
    this.name,
    this.age,
    super.key,
  });
```

**Comment by ikbendewilliam** [comment]
released in v2
