### ISSUE TITLE
No guards error

### ISSUE THREAD

**Issue by luca-vz** [ikbendewilliam/flutter_navigation_generator#18]
In version `2.0.0` you'll get an error when you don't have single guard created, which isn't always needed e.g.: on mobile. The error is caused by `flutter_navigation_generator_annotations` which isn't imported in the generated navigator file. The current workaround would be to create a guard (LoginGuard) with the function `Future<bool> getValue() => Future.value(true);`

**Comment by ikbendewilliam** [comment]
Fixed in 2.0.1
